### ISSUE TITLE
get all evidence IDs without a proper DOID

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-api-client#1]
It would be awesome to add functionality for evidence level filtering so that we could (for example) get all evidence IDs without a proper DOID.

**Comment by gatoravi** [comment]
Hi @obigriffith , could you give this a go -
 `civic-api-client evidence-items-list --doid --max-gene-count 10 --web`

**Comment by obigriffith** [comment]
I'm getting an SSL error. I don't think this has anything to do with the current command.

`requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

**Comment by gatoravi** [comment]
Yeah, I was trying to debug this with @acoffman the other day, this shows up as a one-off on some laptops and then it usually works fine after a while. I'm yet to track down what it is and if it's related to CIViC's certificates, does the error persist?

**Comment by obigriffith** [comment]
Seems to. I tried on imac at work a few times and now at home on my air. With and without going through vpn. 

`(myenv) vpn-10-1-24-220:civic-api-client ogriffit$ civic-api-client evidence-items-list --doid --max-gene-count 10 --web
Traceback (most recent call last):
  File "/Users/ogriffit/git/civic-api-client/myenv/bin/civic-api-client", line 11, in <module>
    sys.exit(main())
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/command_line.py", line 22, in main
    return eil1.main()
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/evidence_items_lister.py", line 93, in main
    vl1.get_civic_genes()
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 181, in get_civic_genes
    self.genes = sorted(requests.get(genes_url).json(), \
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ogriffit/git/civic-api-client/myenv/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

**Comment by acoffman** [comment]
I'm digging into it a little, but it appears at least from an initial look that this has to do with the particular versions of Python, OpenSSL and Requests that are being used.

(From googling the error message: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`) I'll keep looking!

**Comment by gatoravi** [comment]
I set `verify = False` which is not recommended but works around this for now. The updated version of the code should pull this down now. Looking at the output from a week ago and now, I think someone has fixed the evidence items without a proper DOID.
