### ISSUE TITLE
Error when running `civic-api-client variants-list --no-coords --max-gene-count 10`

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-api-client#13]
Hey guys, 

I am getting an error when I try to run this now:

`civic-api-client variants-list --no-coords --max-gene-count 10`

```
Max number of genes to query is  10
Traceback (most recent call last):
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/bin/civic-api-client", line 11, in <module>
    sys.exit(main())
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/command_line.py", line 21, in main
    return vl1.main()
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 249, in main
    self.create_filtered_variants_list()
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 244, in create_filtered_variants_list
    self.filter_variants()
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 210, in filter_variants
    vd1 = VariantDetails(self.args, variant_details)
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 25, in __init__
    self.parse_variant_details(variant_details)
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 47, in parse_variant_details
    self.gene_name = variants['entrez_name']
NameError: global name 'variants' is not defined
```

**Comment by LeiChen0218** [comment]
Hey Malachi,

It was a typo which was fixed in a new branch called fixed_variant_lister_bugshttps://github.com/griffithlab/civic-api-client/tree/fixed_variant_lister_bugs (there’re more changes in the pull request of this branch)
I’m pushing a new commit of that branch now and maybe you can try it 3 min later :)

Lei

On Feb 24, 2016, at 3:29 PM, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey guys,

I am getting an error when I try to run this now:

civic-api-client variants-list --no-coords --max-gene-count 10

Max number of genes to query is  10
Traceback (most recent call last):
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/bin/civic-api-client", line 11, in <module>
    sys.exit(main())
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/command_line.py", line 21, in main
    return vl1.main()
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 249, in main
    self.create_filtered_variants_list()
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 244, in create_filtered_variants_list
    self.filter_variants()
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 210, in filter_variants
    vd1 = VariantDetails(self.args, variant_details)
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 25, in **init**
    self.parse_variant_details(variant_details)
  File "/Users/mgriffit/git/civic/civic-api-client/myenv/lib/python2.7/site-packages/civic_api_client/variants_lister.py", line 47, in parse_variant_details
    self.gene_name = variants['entrez_name']
NameError: global name 'variants' is not defined
